//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCsAdoOmnivox
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int RefStudent { get; set; }
        public string StudentNumber { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Email { get; set; }
    }
}
